<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_5b3f7784dcd49',
    'title' => 'Einrichtungsdaten',
    'fields' => array(
        array(
            'key' => 'field_5b44b9609be7a',
            'label' => 'Adresse:',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'cwd_message',
                'id' => '',
            ),
            'message' => '',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5b44aeb324a1e',
            'label' => 'Straße',
            'name' => 'cwd_str',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '85',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b44aed824a1f',
            'label' => 'Hnr.',
            'name' => 'cwd_hnr',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '15',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b44af0624a20',
            'label' => 'PLZ',
            'name' => 'cwd_plz',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b44b61524a21',
            'label' => 'Ort',
            'name' => 'cwd_ort',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '75',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b50657f35727',
            'label' => 'Kontaktdaten:',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'cwd_message',
                'id' => '',
            ),
            'message' => '',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5b50739732077',
            'label' => 'Ansprechpartner',
            'name' => 'cwd_contact',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b5065a935728',
            'label' => 'Telefon-Nr.',
            'name' => 'cwd_tel',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b5065d235729',
            'label' => 'Fax-Nr.',
            'name' => 'cwd_fax',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b5065f33572a',
            'label' => 'E-Mail',
            'name' => 'cwd_mail',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => 'cwd_auto_height',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_5baca208e0a33',
            'label' => '',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => 'cwd_auto_height',
                'id' => '',
            ),
            'message' => '<span style="font-size:12px;margin-bottom:0;">Sollte es mehrere Ansprechpartner geben, so führen Sie diese bitte unter "Weitere Informationen" an und erläutern Sie kurz deren Zuständigkeiten.</span>',
            'new_lines' => '',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5b506869599fe',
            'label' => 'Weitere Informationen...',
            'name' => 'cwd_infos',
            'type' => 'wysiwyg',
            'instructions' => '...hier ist Platz für beliebige Zusatzinformationen, wie z.B. Sprechzeiten, weiterführende Links, Vorstellungstexte etc.:',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '66.66',
                'class' => 'cwd_float_right',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        array(
            'key' => 'field_5b5066ef8beda',
            'label' => 'Webseite',
            'name' => 'cwd_web',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => 'cwd_auto_height',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'http://example.org',
        ),
        array(
            'key' => 'field_5b44bb6f118ab',
            'label' => 'Standort:',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '75',
                'class' => 'cwd_message',
                'id' => '',
            ),
            'message' => '<i>Die Standortdaten dienen zur Visualisierung/Positionierung der Einrichtung in der Kartenansicht und werden automatisch bestimmt, können bei Bedarf aber manuell angepasst werden. (Sollten die Felder nach dem Speichern der Einrichtung leer bleiben, so konnte die Adresse nicht gefunden werden und eine manuelle Eingabe empfiehlt sich, damit die Einrichtung in der Karteansicht dargestellt werden kann.)</i>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5b44c53fc4abb',
            'label' => 'manuelle Eingabe?',
            'name' => 'cwd_standorteingabe',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => 'cwd_standorteingabe',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5b44bd3f1b2d3',
            'label' => 'lat',
            'name' => 'cwd_lat',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5b44c53fc4abb',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => 'cwd_disabled',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b44bdba1b2d4',
            'label' => 'lng',
            'name' => 'cwd_lng',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5b44c53fc4abb',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => 'cwd_disabled',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b44cd692aec9',
            'label' => '',
            'name' => 'cwd_manueller_standort',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5b44c53fc4abb',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '',
            'center_lng' => '',
            'zoom' => '',
            'height' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'cwd_einrichtung',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5b45c943e85db',
    'title' => 'Einstellungen',
    'fields' => array(
        array(
            'key' => 'field_5b45c9491ad73',
            'label' => 'Seite zur Anzeige der Adressdatenbank:',
            'name' => 'cwd_mainview_id',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        array(
            'key' => 'field_5b61768b8b8d2',
            'label' => 'Seite zur Anzeige des Formulars zum eintragen einer Einrichtung:',
            'name' => 'cwd_registerview_id',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        array(
            'key' => 'field_5b6c444b1c5d3',
            'label' => 'E-Mail Adresse für die Benachrichtigung zur Eintragung einer Einrichtung:',
            'name' => 'cwd_admin_mail',
            'type' => 'email',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_5b6ac7eea8f96',
            'label' => 'Google Maps Api Key',
            'name' => 'cwd_gm_apikey',
            'type' => 'text',
            'instructions' => 'Zur Kartendarstellung und Umkreissuche wird die Google Maps Java Scipt API genutzt, für die Nutzung ist die Einrichtung eines sogenannten "API Key" nötig, weitere Informationen zur Einrichtung finden Sie <a target="__blank" href="https://developers.google.com/maps/documentation/javascript/get-api-key">hier</a>.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'cwd_options',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5bac74be483ba',
    'title' => 'Kontaktdaten',
    'fields' => array(
        array(
            'key' => 'field_5b62dd7b8b364',
            'label' => 'Name',
            'name' => 'cwd_kontakt_name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bac6d50949d8',
            'label' => 'Ihre Position beim Anbieter / in der Einrichtung',
            'name' => 'cwd_kontakt_position',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b62dda18b365',
            'label' => 'Tel.',
            'name' => 'cwd_kontakt_tel',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5b62ddc78b366',
            'label' => 'E-Mail',
            'name' => 'cwd_kontakt_mail',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_5bac6d80949d9',
            'label' => 'Einverständniserklärung',
            'name' => 'cwd_agreement',
            'type' => 'true_false',
            'instructions' => 'Hiermit bestätige ich, dass ich berechtigt bin die Veröffentlichung der Daten zu genehmigen und stimme dieser zu.<br />
In dem Fall, dass ein Foto hochgeladen wurde, erkäre ich hiermit, dass ich die Rechte an diesem Bild besitze und dessen Veröffentlichung ebenfalls zustimme.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'cwd_disabled',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'cwd_einrichtung',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5bf405a42376a',
    'title' => 'Landkreis',
    'fields' => array(
        array(
            'key' => 'field_5bf405b9c83b0',
            'label' => 'Landkreis',
            'name' => 'cwd_landkreis',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'KS Schwerin' => 'Landeshauptstadt Schwerin (kreisfreie Stadt)',
                'KS Rostock' => 'Stadt Rosotck (kreisfreie Stadt)',
                'LK Rostock' => 'Landkreis Rostock',
                'LK Nordwestmecklenburg' => 'Landkreis Nordwestmecklenburg',
                'LK Ludwigslust-Parchim' => 'Landkreis Ludwigslust-Parchim',
                'LK Mecklenburgische Seenplatte' => 'Landkreis Mecklenburgische Seenplatte',
                'LK Vorpommern Greifswald' => 'Landkreis Vorpommern Greifswald',
                'LK Vorpommern Rügen' => 'Landkreis Vorpommern Rügen',
            ),
            'default_value' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5bf4099d3248d',
            'label' => 'Bildquelle',
            'name' => 'cwd_thumbnail_quelle',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Name',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'cwd_einrichtung',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5b61824f123e9',
    'title' => 'new_einrichtung',
    'fields' => array(
        array(
            'key' => 'field_5b62dd2e8b363',
            'label' => 'Kontakt für Rückfragen:',
            'name' => '',
            'type' => 'message',
            'instructions' => 'Diese Daten werden nicht veröffentlicht und dienen nur zum Zweck eventueller Nachfragen.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'cwd_big',
                'id' => '',
            ),
            'message' => '',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5bac767e03b4f',
            'label' => 'Name',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5b62dd7b8b364',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
        array(
            'key' => 'field_5bac775303b50',
            'label' => 'Ihre Position beim Anbieter / in der Einrichtung',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5bac6d50949d8',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
        array(
            'key' => 'field_5bac77b503b51',
            'label' => 'Tel.',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5b62dda18b365',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
        array(
            'key' => 'field_5bac77f303b52',
            'label' => 'E-Mail',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5b62ddc78b366',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
        array(
            'key' => 'field_5b6182cb1f71b',
            'label' => 'Adresse und Kontaktdaten',
            'name' => 'adresse_und_kontaktdaten',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5b44b9609be7a',
                1 => 'field_5b44aeb324a1e',
                2 => 'field_5b44aed824a1f',
                3 => 'field_5b44af0624a20',
                4 => 'field_5b44b61524a21',
                5 => 'field_5b50657f35727',
                6 => 'field_5b50739732077',
                7 => 'field_5b5065a935728',
                8 => 'field_5b5065d235729',
                9 => 'field_5b5065f33572a',
                10 => 'field_5b5066ef8beda',
                11 => 'field_5baca208e0a33',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
        array(
            'key' => 'field_5b6ab2b354a74',
            'label' => 'Kategorie und Angebote:',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => 'cwd_big',
                'id' => '',
            ),
            'message' => 'Bitte wählen Sie rechts die am besten auf Ihre Einrichtung zutreffende Kategorisierung aus und darunter alle Angebote aus der Liste, welche in der Einrichtung zur Verfügung stehen.',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_5b62e47e2a57f',
            'label' => 'Kategorie',
            'name' => 'cwd_register_kategorie',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'angebote',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'id',
            'multiple' => 0,
        ),
        array(
            'key' => 'field_5b62f10e5491e',
            'label' => 'Angebote',
            'name' => 'cwd_register_angebote',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'angebote',
            'field_type' => 'multi_select',
            'allow_null' => 0,
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'id',
            'multiple' => 0,
        ),
        array(
            'key' => 'field_5b6183cffd008',
            'label' => 'Weitere Informationen:',
            'name' => 'cwd_infos',
            'type' => 'wysiwyg',
            'instructions' => 'Hier ist Platz für zusätzliche Informationen, wie z.B. ein kurzer Vorstellungstext zur Einrichtung, Sprechzeiten, weiterführende Links oder ähnliches...',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '66.66',
                'class' => 'cwd_big cwd_italic cwd_no_clear',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
        ),
        array(
            'key' => 'field_5b6837ccb0ab1',
            'label' => 'Vorschaubild zur Einrichtung:',
            'name' => 'cwd_thumbnail',
            'type' => 'image',
            'instructions' => '<small><i>Um eine korrekte Darstellung zu gewährleisten muss das Bild mindestens eine Größe von 400 * 250 px haben und darf dabei aber nicht die Ausmaße von 1920 * 1080 px oder eine Größe von 3 MB überschreiten.</i></small>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => 'cwd_big cwd_auto_height',
                'id' => '',
            ),
            'return_format' => 'id',
            'preview_size' => 'medium',
            'library' => 'uploadedTo',
            'min_width' => 400,
            'min_height' => 250,
            'min_size' => '',
            'max_width' => 1920,
            'max_height' => 1080,
            'max_size' => 3,
            'mime_types' => 'jpg, jpeg, png',
        ),
        array(
            'key' => 'field_5bf3ffa71e7be',
            'label' => 'Quelle:',
            'name' => 'cwd_thumbnail_quelle',
            'type' => 'text',
            'instructions' => '<small><i>Sie müssen die Rechte zur Veröffentlichung des Bilds innehaben und dies unten bei der Einverständniserklärung bestätigen, falls Sie aber gerne den Fotografen namentlich nennen möchten, so haben Sie hier die Möglichkeit dazu.</small></i>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => 'cwd_big cwd_float_right',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Name des Fotografen',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5bac78b1e88a2',
            'label' => 'Einverständniserklärung',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_5bac6d80949d9',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_parent',
                'operator' => '==',
                'value' => '191',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;